<a href="https://colab.research.google.com/github/Neilvaldrez/58013-LinearAlgebra/blob/main/LabNo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#Vector Addition

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

A+B+C

np.add(A,np.add(B,C))
np.sum(B)

2

In [19]:
#Vector Subtraction

np.subtract(A,B)

A-B

array([-2,  1,  2])

In [20]:
#Vector Multiplication

np.multiply(A,B)

A*B

array([3, 2, 0])

In [21]:
#Vector Division

np.divide(A,B)

A/B

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

np.array(A/B,dtype=int)

array([0, 2, 0])