<a href="https://colab.research.google.com/github/Neilvaldrez/58013-LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Define the matrices A, B, C, and D
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4]])

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [5, 6, 7]])

D = np.array([[1, 2],
              [3, 4]])

try:
    result_a = np.dot(A, B)
except ValueError:
    result_a = "Matrix multiplication is not defined for matrices A and B."

result_b = D + D

result_c = 2 * C

print("a. AB =", result_a)

print("\nb. D + D =")
print(result_b)

print("\nc. 2C =")
print(result_c)

a. AB = Matrix multiplication is not defined for matrices A and B.

b. D + D =
[[2 4]
 [6 8]]

c. 2C =
[[ 2  4  6]
 [ 8 10 12]
 [10 12 14]]


In [6]:
import numpy as np

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

CrossP = np.cross(A, B)

print("Cross product of A and B:")
print(CrossP)

Cross product of A and B:
[20 -4 -3]
