<a href="https://colab.research.google.com/github/Neilvaldrez/58013-LinearAlgebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [10]:
import numpy as np
A = np.array([1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10])
result_a = 1 * A
result_b = 2 * A
result_c = 3 * A
result_d = 4 * A
result_e = 5 * A
result_f = 6 * A
result_g = 7 * A
result_h = 8 * A
result_i = 9 * A
result_j = 10 * A

print("Multiplication Table of 1: ", result_a)
print("Multiplication Table of 2: ", result_b)
print("Multiplication Table of 3: ", result_c)
print("Multiplication Table of 4: ", result_d)
print("Multiplication Table of 5: ", result_e)
print("Multiplication Table of 6: ", result_f)
print("Multiplication Table of 7: ", result_g)
print("Multiplication Table of 8: ", result_h)
print("Multiplication Table of 9: ", result_i)
print("Multiplication Table of 10: ", result_j)

Multiplication Table of 1:  [ 1  2  3  4  5  6  7  8  9 10]
Multiplication Table of 2:  [ 2  4  6  8 10 12 14 16 18 20]
Multiplication Table of 3:  [ 3  6  9 12 15 18 21 24 27 30]
Multiplication Table of 4:  [ 4  8 12 16 20 24 28 32 36 40]
Multiplication Table of 5:  [ 5 10 15 20 25 30 35 40 45 50]
Multiplication Table of 6:  [ 6 12 18 24 30 36 42 48 54 60]
Multiplication Table of 7:  [ 7 14 21 28 35 42 49 56 63 70]
Multiplication Table of 8:  [ 8 16 24 32 40 48 56 64 72 80]
Multiplication Table of 9:  [ 9 18 27 36 45 54 63 72 81 90]
Multiplication Table of 10:  [ 10  20  30  40  50  60  70  80  90 100]


Question 2

In [12]:
A = np.array([1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10])
result_2a = 2 * A
result_2b = 4 * A
result_2c = 6 * A
result_2d = 8 * A
result_2e = 10 * A
result_2f = 12 * A
result_2g = 14 * A
result_2h = 16 * A
result_2i = 18 * A
result_2j = 20 * A

print("Multiplication Table of 1*2:", result_2a)
print("Multiplication Table of 2*2:", result_2b)
print("Multiplication Table of 3*2:", result_2c)
print("Multiplication Table of 4*2:", result_2d)
print("Multiplication Table of 5*2:", result_2e)
print("Multiplication Table of 6*2:", result_2f)
print("Multiplication Table of 7*2:", result_2g)
print("Multiplication Table of 8*2:", result_2h)
print("Multiplication Table of 9*2:", result_2i)
print("Multiplication Table of 10*2:", result_2j)

Multiplication Table of 1*2: [ 2  4  6  8 10 12 14 16 18 20]
Multiplication Table of 2*2: [ 4  8 12 16 20 24 28 32 36 40]
Multiplication Table of 3*2: [ 6 12 18 24 30 36 42 48 54 60]
Multiplication Table of 4*2: [ 8 16 24 32 40 48 56 64 72 80]
Multiplication Table of 5*2: [ 10  20  30  40  50  60  70  80  90 100]
Multiplication Table of 6*2: [ 12  24  36  48  60  72  84  96 108 120]
Multiplication Table of 7*2: [ 14  28  42  56  70  84  98 112 126 140]
Multiplication Table of 8*2: [ 16  32  48  64  80  96 112 128 144 160]
Multiplication Table of 9*2: [ 18  36  54  72  90 108 126 144 162 180]
Multiplication Table of 10*2: [ 20  40  60  80 100 120 140 160 180 200]


Question 3

In [13]:
c = np.eye(4,4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 4

In [10]:
import numpy as np

matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print("The size of the matrix is\n", matrix)

ball = np.shape(matrix)
print("The shape/dimension of the matrix is", ball)



The size of the matrix is
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The shape/dimension of the matrix is (3, 4)


Question 5

In [7]:
import numpy as numpy

arrayOne = numpy.array([[5,6,9],[21,18,27]])
arrayTwo = numpy.array([[15,33,24],[4,7,1]])
arrayAdd = np.add(arrayOne,arrayTwo)
print("The added values of arrayOne and arrayTwo are:\n", arrayAdd)

arraySquare = np.square(arrayAdd)
print("The squared values of the added values are:\n", arraySquare)

The added values of arrayOne and arrayTwo are:
 [[20 39 33]
 [25 25 28]]
The squared values of the added values are:
 [[ 400 1521 1089]
 [ 625  625  784]]
