<a href="https://colab.research.google.com/github/Neilvaldrez/58013-LinearAlgebra/blob/main/PythonExercise9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#Commutative Property of Matrix Multiplication
import numpy as np

C = np.array([
    [6, 3, 7],
    [6, 5, 3],
    [4, 9, 8]
])

D = np.array([
    [2, 8, 1],
    [5, 7, 6],
    [9, 4, 2]
])

result_CD = np.dot(C, D)

result_DC = np.dot(D, C)

commutative_property = np.array_equal(result_CD, result_DC)

print("Matrix C * D:")
print(result_CD)
print("Matrix D * C:")
print(result_DC)
print("Commutative Property:", commutative_property)


Matrix C * D:
[[ 90  97  38]
 [ 64  95  42]
 [125 127  74]]
Matrix D * C:
[[ 64  55  46]
 [ 96 104 104]
 [ 86  65  91]]
Commutative Property: False


In [18]:
#Associative Property of Matrix Multiplication
import numpy as np

C = np.array([
    [6, 3, 7],
    [6, 5, 3],
    [4, 9, 8]
])

A = np.array([
    [2, 1, 3],
    [5, 2, 4],
    [7, 2, 1]
])

B = np.array([
    [9, 2, 6],
    [1, 7, 5],
    [3, 8, 2]
])

result_AB_C = np.dot(np.dot(A, B), C)

result_A_BC = np.dot(A, np.dot(B, C))

associative_property = np.array_equal(result_AB_C, result_A_BC)

print("Matrix (A * B) * C:")
print(result_AB_C)
print("Matrix A * (B * C):")
print(result_A_BC)
print("Associative Property:", associative_property)


Matrix (A * B) * C:
[[ 470  466  485]
 [ 882  889  965]
 [ 840  870 1016]]
Matrix A * (B * C):
[[ 470  466  485]
 [ 882  889  965]
 [ 840  870 1016]]
Associative Property: True


In [24]:
#Multiplicative Identity Property of Matrix Multiplication
import numpy as np

C = np.array([
    [6, 3, 7],
    [6, 5, 3],
    [4, 9, 8]
])

I = 1
IC = np.dot(I,C)
CI = np.dot(C,I)

print("Array C:\n",C,"\nProduct of I*C:\n",IC,"\nProduct of C*I:\n",CI)
print("From these arrays, IC=CI, and CI=C.")

Array C:
 [[6 3 7]
 [6 5 3]
 [4 9 8]] 
Product of I*C:
 [[6 3 7]
 [6 5 3]
 [4 9 8]] 
Product of C*I:
 [[6 3 7]
 [6 5 3]
 [4 9 8]]
From these arrays, IC=CI, and CI=C.


In [23]:
#Multiplicative Property of Zero

O = 0
OC = np.dot(O,C)
CO = np.dot(C,O)

print("Array C:\n",C,"\nThe Product of O and C:\n",OC,"\nThe Product of C and O:\n",CO)
print("Therefore, OC = 0, and CO = 0.")

Array C:
 [[6 3 7]
 [6 5 3]
 [4 9 8]] 
The Product of O and C:
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 
The Product of C and O:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Therefore, OC = 0, and CO = 0


In [31]:
#Dimension Property of Matrix Multiplication

E = np.array([
    [6, 3],
    [6, 5],
    [4, 9]
])

F = np.array([
    [2, 3, 5],
    [3, 0, 1]
])

ShapeE = np.shape(E)
ShapeF = np.shape(F)
dProduct = np.dot(ShapeE[])


TypeError: ignored