<a href="https://colab.research.google.com/github/Neilvaldrez/58013-LinearAlgebra/blob/main/Vector%2C_Spaces%2C_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Shape of the Matrices

In [51]:
#Size Dimension, Size
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls
print(z)


[1 2 3]
[ 0  1 -1]
(3, 3)
1


Vector Operations

In [57]:
#Addition
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])
aR = np.add(A,B)

print(R)

[ 6 -2]


In [91]:
#Subtraction
sR1 = np.subtract(A,B)
print(sR1)
sR2 = np.subtract(B,A)
print(sR2)

[[2 1]
 [9 8]]
[[-2 -1]
 [-9 -8]]


In [83]:
#Multiplication
mR = np.multiply(A,B)
print(mR)

[[  8   6]
 [-20 -15]]


In [88]:
#Division
dR = np.divide(A,B)
print(dR)

[[ 2.   1.5]
 [-0.8 -0.6]]


In [62]:
#Scalar Product
S = np.array([2])
V = S*A
print(V)

[8 6]


In [68]:
#Dot Product
dP = np.dot(A,B)
print(dP)

-7


In [69]:
#Cross Product
cP = np.cross(A,B)
print(cP)

-26


In [95]:
#Properties of Matrix
#Identity Matrix
c = np.eye(3,3)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)

#Full Matrix
e = np.full((3,3),7)
print(e)

#Transpose Matrix
f = np.transpose(mR)
print(f)

#Null Matrix
g = np.empty([3,3])
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
